apiVersion: v1
kind: Pod
metadata:
  name: storybook-deployment
spec:
  selector:
    matchLabels:
      app: storybook
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: storybook
    spec:
      containers:
      - name: storybook
        image: storybook:latest
        ports:
        - containerPort: 80
